### ISSUE TITLE
Great podcast - small request for show notes.

### ISSUE THREAD

**Issue by EdmundsEcho** [haskellweekly/podcast#4]
Thank you for putting together this podcast.  It is truly a useful resource.  My only, small request: Would it be possible to take no more than 10-15 min to jot down code snippets that describe the concept or topic discussed?  Even if it were a paragraph, or 10-15 lines of code would go a long way.

**Comment by tfausak** [comment]
Hi! Thanks for the kind words, and for a solid suggestion. This hadn't occurred to me yet because typically we're talking about a blog post. More often than not, that blog post has some example code that covers what we're talking about. For example, the most recent episode about profiling links to a blog post that has Haskell code, shell commands, and profiler output. Are you asking to include that stuff in the show notes?

**Comment by EdmundsEcho** [comment]
You're welcome.  In the example you are describing, even notes that included the links to the blog would be helpful.  I might be missing something, but I could not find anything.

**Comment by tfausak** [comment]
The link shows up for me in iTunes, although it's not actually clickable:

![Screen Shot 2019-06-03 at 9 51 40 AM](https://user-images.githubusercontent.com/408753/58806999-47326200-85e5-11e9-9274-a38b282ea6fa.png)

The same is true on the episode page itself: https://haskellweekly.news/podcast/episodes/11.html

If those were clickable, would that work for you?

**Comment by EdmundsEcho** [comment]
Yes.  Believe it or not, that would go a long way.  I'm not sure I even noticed the link before.
